### ISSUE TITLE
How do I offline use it？

### ISSUE THREAD

**Issue by ClockQ** [rembik/ansible-role-kickstart-iso#4]
##### SUMMARY
I'm sorry，me English not good. But I need to use your ansible role in offline environment. How write of your vars URL.

- kickstart_iso_check_url
- kickstart_iso_base_url
- kickstart_iso_install_media

Thank you.

##### ISSUE TYPE
- Feature Idea

**Comment by rembik** [comment]
With the release v1.7.5 you will be able to use the role without network connection. Therefore the base ISO image you reference to need to be placed at kickstart_iso_src_dir before running this role, of course.

```
- name: CentOS 8 (offline)
  include_role:
    name: rembik.kickstart_iso
  vars:
    kickstart_iso_src_file:
      name: 'CentOS-8.4.2105-x86_64-dvd1.iso'
      checksum: '0394ecfa994db75efc1413207d2e5ac67af4f6685b3b896e2837c682221fd6b2'
    kickstart_iso_install_media: 'cdrom'
```
